services:
#  frontend:
#    build: frontend/
#    ports:
#      - "80:80"
#    depends_on:
#      - api-gateway

  config-service:
    build: config-service/
    ports:
      - "8888"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5

  discovery-service:
    build: discovery-service/
    ports:
      - "8761"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8761/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build: api-gateway/
    ports:
      - "8080:8080"
    depends_on:
      discovery-service:
        condition: service_healthy