services:
  frontend:
    build: frontend/
    ports:
      - "80:80"

  config-service:
    build: config-service/
    ports:
      - "8888"

  discovery-service:
    build: discovery-service/
    ports:
      - "8761"
    depends_on:
      - config-service