services:
  frontend:
    build: frontend/
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  config-service:
    build: config-service/
    ports:
      - "8888"

  discovery-service:
    build: discovery-service/
    ports:
      - "8761"
    depends_on:
      - config-service

  api-gateway:
    build: api-gateway/
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service