services:
  frontend:
    build: frontend/
    ports:
      - "80:80"
    depends_on:
      api-gateway:
        condition: service_healthy

  config-service:
    build: config-service/
    ports:
      - "8888"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5

  discovery-service:
    build: discovery-service/
    ports:
      - "8761"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5

  api-gateway:
    build: api-gateway/
    ports:
      - "8080:8080"
    depends_on:
      authentication-service:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5

  authentication-service:
    build: authentication-service/
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres-service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5

  redis-service:
    image: "redis:latest"
    ports:
      - "6379"
    healthcheck:
      test: "redis-cli ping | grep PONG || 0"
      interval: 20s
      timeout: 10s
      retries: 5

  postgres-service:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=radio-active-mushroom-DB"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432"
    healthcheck:
      test: "pg_isready || 0"
      interval: 20s
      timeout: 10s
      retries: 5