server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
        #configserver
        service-id: config-service
      server:
        native:
          search-locations: classpath:/config